name: Build and Deploy

on:
  push:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  build-n-test:
    uses: ./.github/workflows/build-n-test.yml
    with:
      target: unittests
  
  generate-docs:
    needs: build-n-test
    uses: ./.github/workflows/generate-docs.yml

  deploy-docs:
    needs: generate-docs
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
