name: CMake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  # Customize the CMake build type here (Release, Debug, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Executables
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ${{github.workspace}}/build
    - name: Debug
      shell: bash
      run: pwd && ls -la
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: sudo ctest -C $BUILD_TYPE
