name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  generate-docs:
    uses: ./.github/workflows/generate-docs.yml

  deploy-preview:
    needs: generate-docs
    concurrency: preview-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
